name: Build Image

on:
  release:
    types: [published]
  push:

env:
  IMAGE: "tailscale-mod"
  USER: "chukysoria"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        id: build-time
        run: echo "NOW=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Login to Github Container Repo
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.0
        with:
          # list of Docker images to use as base name for tags
          images: |
              ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}            
          # generate Docker tags based on the following events/attributes
          flavor: 
            latest=true
          tags: |
            type=sha,prefix=,suffix=-${{ github.ref_name }}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=semver,pattern=v{{major}}.{{minor}}
          labels: |
            org.opencontainers.image.created=${{ steps.build-time.outputs.NOW }}
            org.opencontainers.image.authors=Chukysoria
            org.opencontainers.image.url=https://github.com/${{ env.USER }}/docker-mod/packages
            org.opencontainers.image.source=https://github.com/chukysoria/docker-mod
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.vendor=Chukysoria
            org.opencontainers.image.licenses=GPL-3.0-only
            org.opencontainers.image.ref.name=${{ github.sha }}
            org.opencontainers.image.title=${{ env.IMAGE }}  

      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          push: ${{ github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          pull: true
